### ISSUE TITLE
No UI indication on how to use the syringe

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#10]
![image](https://user-images.githubusercontent.com/52638056/180615034-2a98e13f-a1b4-4ab2-9850-dce5f1044822.png)

**Comment by smallelephant9516** [comment]
That might be the reason for the failure in #3

**Comment by SchubyDong** [comment]
I have made a new interaction. Please give it a try

**Comment by smallelephant9516** [comment]
It is easy to do now
