### ISSUE TITLE
Progress bar when pouring the LN

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#11]
There is no progress bar for pouring the LN
![image](https://user-images.githubusercontent.com/52638056/180615112-782fa595-89b3-4477-920d-ea65d96a3936.png)
![image](https://user-images.githubusercontent.com/52638056/180615117-40accb45-f9bb-462d-b70f-20f05333751c.png)

**Comment by SchubyDong** [comment]
Progress bars added for both cooldown and ethane
