### ISSUE TITLE
A step to put the grid box into the dewar with LN

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#16]
Currently, there is just a step to take out the grid box
![image](https://user-images.githubusercontent.com/52638056/180615298-9a05cf39-cf5f-42e3-adc4-d77ad36639f5.png)

**Comment by SchubyDong** [comment]
I have made a simple step for it. But further steps like adding LN to the freeze dewar need more time to complete

**Comment by smallelephant9516** [comment]
Also please add a UI indication for the dewar

**Comment by smallelephant9516** [comment]
![image](https://user-images.githubusercontent.com/52638056/181136965-664cc126-3ad8-4f09-b89a-c8d5613c2e4b.jpeg)

**Comment by SchubyDong** [comment]
Highlight of freeze dewar has been added
