### ISSUE TITLE
No quit game button

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#17]

**Comment by SchubyDong** [comment]
I have added a quit game button to the right

**Comment by smallelephant9516** [comment]
The quit game button is too small

**Comment by smallelephant9516** [comment]
![image](https://user-images.githubusercontent.com/52638056/181136935-27b9aac0-a80e-407f-8f29-fcfa1d8a7878.jpeg)

**Comment by SchubyDong** [comment]
Made it 1.5 times bigger
