### ISSUE TITLE
The UI of indication on the screen is too dark

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#18]
The green UI is too dark for other people to see the content
![image](https://user-images.githubusercontent.com/52638056/180620859-c8ffd052-d94b-4ef8-95e2-eff05700781f.png)

**Comment by SchubyDong** [comment]
I have made it slightly lighter. Please give it a try

**Comment by smallelephant9516** [comment]
Fixed

**Comment by smallelephant9516** [comment]
Still too dark sometimes

**Comment by smallelephant9516** [comment]
![image](https://user-images.githubusercontent.com/52638056/181136915-884cf366-6d24-4f86-8979-4187e5ca54ce.jpeg)
