### ISSUE TITLE
The interaction for using the syringe is wired

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#3]
It is hard to finish this step. There is no response when I first grab it and use another hand to continue this step. It is only when I drop it on the desk and then this step can be continued.
![image](https://user-images.githubusercontent.com/52638056/170358188-b573fa9c-90fd-4047-aaad-feb5ae2b3a17.jpeg)

**Comment by smallelephant9516** [comment]
I think this might be our highest priority as most people would get stuck in this step.

**Comment by SchubyDong** [comment]
please refer to #10

**Comment by smallelephant9516** [comment]
Seems good now
