### ISSUE TITLE
The steps for attaching the grid

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#5]
There is no steps for attaching the grid. 
![image](https://user-images.githubusercontent.com/52638056/170779318-c32b8497-d414-4427-8d18-a3f465961bbe.jpeg)

**Comment by smallelephant9516** [comment]
This step has to be done.

**Comment by SchubyDong** [comment]
I have added the steps

**Comment by smallelephant9516** [comment]
The step has been added
