### ISSUE TITLE
No process of adding ethane

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#7]
When you use the tip to interact with the work station, the whole process of adding ethane is finished. There is no time or progress for the adding ethane
![image](https://user-images.githubusercontent.com/52638056/170779922-4a311ff4-2032-41a9-b8e7-35362c1f695d.jpeg)

**Comment by SchubyDong** [comment]
same as question above

**Comment by smallelephant9516** [comment]
The waiting time of adding ethane and LN is too long, it is the same problem, so the LN one is closed

**Comment by SchubyDong** [comment]
Now it's 5s instead of 10s
