### ISSUE TITLE
Strange rubber tube

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_Leica-EM-GP2#9]
When the cold box move up. The rubber tube extend strange making the syringe looks like sticking on the table.

![image](https://user-images.githubusercontent.com/52638056/170782310-e9613747-6099-40db-8358-1bebb9055b87.jpeg)

**Comment by SchubyDong** [comment]
This has been improved

**Comment by smallelephant9516** [comment]
Looks good now
